# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex's Mediocre site
email: Alexander_M_Clarke@live.co.uk
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

socials:
  -
    name: Github
    link: https://github.com/Alex-CD
    icon: github.svg
  -
    name: Twitter
    link: https://twitter.com/AlexCDev
    icon: twitter.svg
  -
    name: linkedin
    link: https://www.linkedin.com/in/alexcdev/
    icon: linkedin.svg
  -
    name: email
    link: mailto:alexander_m_clarke@live.co.uk
    icon: protonmail.svg


# Build settings
markdown: kramdown

collections:
  - projects
  - jobs
  - volunteering

sass:
style: compressed
sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
